# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='城市名')),
                ('description', models.CharField(max_length=32, verbose_name='城市简述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='课程机构名')),
                ('description', models.CharField(max_length=32, verbose_name='机构简述')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('address', models.CharField(max_length=64, verbose_name='机构地址')),
                ('phone_num', models.CharField(max_length=16, verbose_name='联系方式')),
                ('image', models.ImageField(default='organization/default.png', max_length=128, upload_to='organization/%Y/%m', verbose_name='机构封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '课程机构',
                'verbose_name_plural': '课程机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='讲师名')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_company', models.CharField(blank=True, max_length=32, null=True, verbose_name='供职单位')),
                ('work_position', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司职位')),
                ('characters', models.TextField(blank=True, null=True, verbose_name='讲师风格')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('phone_num', models.CharField(max_length=16, verbose_name='联系方式')),
                ('image', models.ImageField(default='organization/teachers/default.png', max_length=128, upload_to='organization/teahers/%Y/%m', verbose_name='讲师照片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '讲师信息',
                'verbose_name_plural': '讲师信息',
            },
        ),
    ]
