# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('trainingorg', '培训机构'), ('university', '高校'), ('personal', '个人')], default='trainingorg', max_length=32, verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='organization/default.png', max_length=128, upload_to='organization/%Y/%m', verbose_name='Logo'),
        ),
    ]
