# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170427_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='organization/mooc.jpg', max_length=128, upload_to='organization/%Y/%m', verbose_name='Logo'),
        ),
    ]
