# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170503_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='机构简述'),
        ),
    ]
