# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.CharField(default='Python Framework', max_length=64, verbose_name='课程类别'),
            preserve_default=False,
        ),
    ]
