# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_gain',
            field=models.TextField(blank=True, null=True, verbose_name='你将学到'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_notice',
            field=models.TextField(default='OK', verbose_name='课程须知'),
            preserve_default=False,
        ),
    ]
