# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20170508_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=64, verbose_name='章节名'),
        ),
    ]
