# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=128, verbose_name='视频名称'),
        ),
    ]
