# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20170511_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learning_time',
            field=models.IntegerField(default=0, verbose_name='学习时长(单位:分钟)'),
        ),
    ]
