# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_video_learning_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', verbose_name='访问地址'),
        ),
    ]
