# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20170524_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.IntegerField(default=0, verbose_name='发送类型或者接收用户ID'),
        ),
    ]
