# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget_password', '忘记密码')], default='register', max_length=16, verbose_name='验证类型'),
        ),
    ]
