# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170419_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=16, verbose_name='验证码'),
        ),
    ]
