# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170422_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/superman.jpg', max_length=128, upload_to='image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
